name: fam_flutter_storyapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.2
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_keychain: ^2.4.0
  flutter_localization: ^0.1.14
  flutter_screenutil: ^5.9.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: ^0.18.0
  meta: ^1.9.0
  package_info_plus: ^4.2.0
  provider: ^6.0.5
  screenshot: ^2.1.0
  skeletons: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
